# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cMakeModel <- function(initValues, initData, initPriors) {
    .Call('_icenME_cMakeModel', PACKAGE = 'icenME', initValues, initData, initPriors)
}

c_get_ab_vals <- function(model) {
    .Call('_icenME_c_get_ab_vals', PACKAGE = 'icenME', model)
}

c_get_gmus_vals <- function(model, ind) {
    .Call('_icenME_c_get_gmus_vals', PACKAGE = 'icenME', model, ind)
}

c_get_gamma_vals <- function(model, ind1, ind2) {
    .Call('_icenME_c_get_gamma_vals', PACKAGE = 'icenME', model, ind1, ind2)
}

c_set_ab <- function(model, new_vals) {
    invisible(.Call('_icenME_c_set_ab', PACKAGE = 'icenME', model, new_vals))
}

c_setAndCalc_ab <- function(model, new_vals) {
    .Call('_icenME_c_setAndCalc_ab', PACKAGE = 'icenME', model, new_vals)
}

c_set_gmus <- function(model, new_vals, ind) {
    invisible(.Call('_icenME_c_set_gmus', PACKAGE = 'icenME', model, new_vals, ind))
}

c_setAndCalc_gmus <- function(model, new_vals, ind) {
    .Call('_icenME_c_setAndCalc_gmus', PACKAGE = 'icenME', model, new_vals, ind)
}

c_set_gamma <- function(model, new_vals, ind1, ind2) {
    invisible(.Call('_icenME_c_set_gamma', PACKAGE = 'icenME', model, new_vals, ind1, ind2))
}

c_setAndCalc_gamma <- function(model, new_vals, ind1, ind2) {
    .Call('_icenME_c_setAndCalc_gamma', PACKAGE = 'icenME', model, new_vals, ind1, ind2)
}

n_gmus <- function(model) {
    .Call('_icenME_n_gmus', PACKAGE = 'icenME', model)
}

n_gamma <- function(model, gamma_l1) {
    .Call('_icenME_n_gamma', PACKAGE = 'icenME', model, gamma_l1)
}

c_full_lp <- function(model) {
    .Call('_icenME_c_full_lp', PACKAGE = 'icenME', model)
}

